### ISSUE TITLE
Artik 530s: Need module headers

### ISSUE THREAD

**Issue by andrewjaykeller** [resin-io-playground/kernel-module-build#11]
Expected to be able to run this program on artik 530s however the build failed with:

```bash
Could not find headers for 'artik533s' at version 'v2.15.1+rev2.prod', run ./build.sh --list
```

**Comment by andrewjaykeller** [comment]
@floion any ideas on if the same patch for the jetson tx2 needs to be done for artik 530s? See #4

**Comment by floion** [comment]
Hi, @vicgal can you check and deploy headers for this board too?

**Comment by vicgal** [comment]
Hi @floion, @andrewjaykeller,

We just merged some improvements to the test app : https://github.com/balena-io-playground/kernel-module-build and,  I will deploy 2.29 for Artik, but looking at Andrew's log,  it seems that there is an extra 'v' in the version in the Dockerfile.template: 'v2.15.1+rev2.prod' should be '2.15.1+rev2.prod'. Andrew please give it try with the new test app and the correct version.

**Comment by floion** [comment]
artik530s has been deprecated so closing this issue
