### ISSUE TITLE
No headers for 2.32.0+rev2.prod on Raspberry Pi 3

### ISSUE THREAD

**Issue by daghemo** [resin-io-playground/kernel-module-build#23]
It seems that someone forgot to publish the header files for 2.32.0+rev2.prod.
Just using 2.32.0+rev1.prod seems to work.

**Comment by floion** [comment]
Hi. Version 2.32.0+rev2 is not released to production for rpi3

**Comment by daghemo** [comment]
Sorry, I didn't noticed that you moved from "2.32.0+rev1.prod" to "2.36.0+rev2.prod", not "2.32.0+rev2.prod"!
