### ISSUE TITLE
Odroid-XU4

### ISSUE THREAD

**Issue by GWysz** [resin-io-playground/kernel-module-build#5]
Thank you for this example, it shall suit my needs, but unfortunately it fails to complete:

root@odroid-ux3:/usr/src/app/kernel-module-build# ./build.sh odroid-xu4 1.24.0 example_module
Building images/odroid-xu4/1.24.0/kernel_modules_headers.tar.gz...
--2017-12-15 08:47:17--  https://files.resin.io/images/odroid-xu4/1.24.0/kernel_modules_headers.tar.gz
Resolving files.resin.io (files.resin.io)... 54.83.178.117, 34.225.84.11
Connecting to files.resin.io (files.resin.io)|54.83.178.117|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8857721 (8.4M) [application/x-tar]
Saving to: 'kernel_modules_headers.tar.gz'

kernel_modules_headers.tar.gz                               100%[===========================================================================================================================================>]   8.45M   129KB/s    in 37s

2017-12-15 08:47:55 (234 KB/s) - 'kernel_modules_headers.tar.gz' saved [8857721/8857721]

make: Entering directory '/tmp/tmp.lpTZxPltET'
  CC [M]  /usr/src/app/kernel-module-build/example_module_odroid-xu4_1.24.0/hello.o
/tmp/tmp.lpTZxPltET/scripts/recordmcount: 2: /tmp/tmp.lpTZxPltET/scripts/recordmcount: Syntax error: "(" unexpected
scripts/Makefile.build:314: recipe for target '/usr/src/app/kernel-module-build/example_module_odroid-xu4_1.24.0/hello.o' failed
make[1]: *** [/usr/src/app/kernel-module-build/example_module_odroid-xu4_1.24.0/hello.o] Error 2
Makefile:1232: recipe for target '_module_/usr/src/app/kernel-module-build/example_module_odroid-xu4_1.24.0' failed
make: *** [_module_/usr/src/app/kernel-module-build/example_module_odroid-xu4_1.24.0] Error 2
make: Leaving directory '/tmp/tmp.lpTZxPltET'

**Comment by floion** [comment]
Hi, we have a new OS release version v2.9.7+rev2 for the Odroid XU4.
Can you try with this new release please?
