### ISSUE TITLE
With UDEV=1 X11 keyboard + mouse drivers aren't detected

### ISSUE THREAD

**Issue by parker-hologram** [resin-io-playground/kernel-module-build#51]
**Solved with this PR: https://github.com/balena-os/kernel-module-build/pull/50** 

When using the kernel module to compile a driver, the new entry point provided in the template stops X11 keyboard + mouse drivers from working

**Comment by floion** [comment]
PR https://github.com/balena-os/kernel-module-build/pull/50 merged
Thanks for creating the issue
