### ISSUE TITLE
Possible Environment Issue

### ISSUE THREAD

**Issue by jtsmedley** [resin-io-playground/kernel-module-build#6]
I have to run the RUN declaration as bash instead of directly calling ./

RUN bash build.sh %%RESIN_MACHINE_NAME%% '2.12.5+rev1.prod' GobiNet 
RUN bash build.sh %%RESIN_MACHINE_NAME%% '2.12.5+rev1.prod' GobiSerial

**Comment by agherzan** [comment]
I just tested the example module here and it worked without this change. Can you check the permissions of the build.sh script?
